name: publish
on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      ELM_HOME: "${GITHUB_WORKSPACE}"
    steps:
    - name: clone
      uses: actions/checkout@master

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.15.3'
    - run: npm ci
    - run: npm run build-prod

    - name: publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: target/vela-ui
        cache: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}