name: validate
on:
  pull_request:
  push:
      
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ELM_HOME: "${GITHUB_WORKSPACE}"
    steps:
    - name: clone
      uses: actions/checkout@v1
      
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.15.3'
    - run: npm ci
    - run: npm i elm-format
    - run: npx elm-format --validate src/ tests/